import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {safeUrl,driveId,thumbnail,validate,selectWorks,SUBJECTS} from '../src/domain.js';
const valid={title:'Siklus Air Interaktif',description:'Media pembelajaran siklus air untuk siswa sekolah dasar kelas lima.',category:'IPAS',gradeClass:'Kelas 5',tags:['siklus air'],creatorName:'Guru Penguji',creatorSchool:'Sekolah Penguji',link:'https://contoh.vercel.app/air?kelas=5',aiStudioLink:'https://aistudio.google.com/apps/drive/123',thumbnail:'https://drive.google.com/file/d/abcdefghijk123456/view',literacySheetFile:'https://drive.google.com/open?id=abcdefghijk123456',literacySheetName:'Lembar Literasi Siklus Air'};
test('HTTPS menerima berbagai hosting dan menolak URL lokal/berbahaya',()=>{for(const u of ['https://contoh.netlify.app','https://contoh.vercel.app','https://contoh.github.io/air','https://contoh.pages.dev','https://sekolah.sch.id'])assert.equal(safeUrl(u),true,u);for(const u of ['http://example.com','javascript:alert(1)','data:text/html,1','https://localhost','https://127.0.0.1','https://10.0.0.1','https://172.16.0.1','https://192.168.1.1','https://2130706433','https://0x7f000001','https://[::1]','https://user:pass@example.com'])assert.equal(safeUrl(u),false,u)});
test('Parser Drive dan validasi seluruh field',()=>{for(const u of ['https://drive.google.com/file/d/abcdefghijk123456/view','https://drive.google.com/open?id=abcdefghijk123456','https://drive.google.com/uc?id=abcdefghijk123456','https://drive.google.com/thumbnail?id=abcdefghijk123456'])assert.equal(driveId(u),'abcdefghijk123456');assert.equal(driveId('https://evil.com/file/d/abcdefghijk123456'),'');assert.deepEqual(validate(valid),{});assert.ok(validate({...valid,tags:Array(9).fill('tag')}).tags);assert.ok(validate({...valid,category:'Tidak ada'}).category);assert.ok(validate({...valid,aiStudioLink:'https://aistudio.google.com.evil.com'}).aiStudioLink)});
test('Pencarian lintas field, filter gabungan dan pengurutan',()=>{const data=SUBJECTS.map((c,i)=>({id:String(i),title:'Media '+c,description:'Eksplorasi',creatorName:'Rini',creatorSchool:'SD Pelita',category:c,gradeClass:i%2?'Kelas 4':'Kelas 5',tags:['interaktif'],dateAdded:'2026-09-'+String(i+1).padStart(2,'0'),views:i,likes:10-i}));assert.equal(selectWorks(data,{q:'PELITA',category:'IPAS',grade:'Kelas 5'}).length,1);assert.equal(selectWorks(data,{q:'interaktif'}).length,10);assert.equal(selectWorks(data,{sort:'likes'})[0].id,'0');assert.equal(selectWorks(data,{sort:'views'})[0].id,'9');assert.equal(selectWorks(data)[0].id,'9');assert.equal(selectWorks(data,{q:'tidak ada'}).length,0)});
function backend(){const rows=[],cache=new Map(),writes=[];let locked=false;const sheet={getName:()=> 'MateriGuruSD',getMaxColumns:()=>17,getLastRow:()=>rows.length,setFrozenRows(){},getRange(r,c,n=1,m=1){return {getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>rows[r-1+i]?.[c-1+j]??'')),getValue:()=>rows[r-1]?.[c-1]??'',setValue(v){assert.equal(locked,true,'write requires lock');rows[r-1]??=[];rows[r-1][c-1]=v;writes.push([r,c])},setValues(v){assert.equal(locked,true,'write requires lock');v.forEach((row,i)=>{rows[r-1+i]??=[];row.forEach((cell,j)=>{rows[r-1+i][c-1+j]=cell;writes.push([r+i,c+j])})})}}}};
const ctx=vm.createContext({console:{log(){}},Date,JSON,Math,Number,String,Array,Object,Error,isFinite,ContentService:{MimeType:{JSON:'json'},createTextOutput(s){return {setMimeType(){return JSON.parse(s)}}}},PropertiesService:{getScriptProperties:()=>({getProperty:()=>null})},SpreadsheetApp:{getActiveSpreadsheet:()=>({getSheetByName:()=>sheet}),flush(){}},CacheService:{getScriptCache:()=>({get:k=>cache.get(k),put:(k,v)=>cache.set(k,v)})},LockService:{getScriptLock:()=>({tryLock:()=>{locked=true;return true},waitLock:()=>{locked=true},releaseLock:()=>{locked=false}})},Utilities:{newBlob:s=>({getBytes:()=>Buffer.from(s)}),formatDate:d=>d.toISOString().slice(0,10),getUuid:()=>crypto.randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>crypto.createHash('sha256').update(s).digest(),base64EncodeWebSafe:b=>Buffer.from(b).toString('base64url')}});vm.runInContext(fs.readFileSync(new URL('../backend/Code.gs',import.meta.url),'utf8'),ctx);rows.push([...ctx.HEADERS]);return {ctx,rows,writes,post:p=>ctx.doPost({postData:{contents:JSON.stringify(p)}})}}
test('Backend mengabaikan ID/counter client, menjaga link internal, dan mengisolasi counter',()=>{const b=backend();const result=b.post({action:'create',...valid,id:'overwrite-me',views:99,likes:99,isFeatured:true});assert.equal(result.status,'success');assert.notEqual(result.id,'overwrite-me');assert.equal(b.rows.length,2);assert.deepEqual(b.rows[1].slice(11,14),[0,0,false]);assert.equal(b.rows[1][14],valid.aiStudioLink);const pub=b.ctx.doGet();assert.equal(pub.count,1);assert.equal(JSON.stringify(pub).includes('aistudio'),false);assert.equal('aiStudioLink' in pub.data[0],false);const before=JSON.stringify(b.rows[1]);assert.equal(b.post({action:'create',...valid}).id,result.id);assert.equal(b.rows.length,2);assert.equal(JSON.stringify(b.rows[1]),before);for(const [action,col] of [['view',12],['like',13]]){b.writes.length=0;assert.equal(b.post({action,id:result.id,title:'HACK'}).status,'success');assert.deepEqual(b.writes,[[2,col]])}assert.equal(b.post({action:'delete',id:result.id}).code,'INVALID_ACTION')});
test('Backend memvalidasi input, formula, honeypot, sheet kosong, dan rate limit',()=>{const b=backend();assert.equal(b.ctx.doGet().count,0);assert.equal(b.ctx.sheetText_(' =SUM(A1)'),"'=SUM(A1)");assert.equal(b.post({action:'create',...valid,website:'bot'}).code,'VALIDATION_ERROR');assert.equal(b.post({action:'create',...valid,link:'https://127.0.0.1'}).code,'VALIDATION_ERROR');assert.equal(b.post({action:'create',...valid,extra:'x'.repeat(22000)}).code,'VALIDATION_ERROR');for(let i=0;i<5;i++)assert.equal(b.post({action:'create',...valid,title:'Media nomor '+i}).status,'success');assert.equal(b.post({action:'create',...valid,title:'Media nomor 6'}).code,'RATE_LIMITED');assert.equal(b.post({action:'view',id:'missing'}).code,'NOT_FOUND')});


test('Deskripsi panjang diterima utuh, batas minimum tetap berlaku',()=>{const long='Pembelajaran interaktif. '.repeat(1000);assert.deepEqual(validate({...valid,description:long}),{});assert.ok(validate({...valid,description:'terlalu singkat'}).description);const b=backend();assert.equal(b.post({action:'create',...valid,description:long}).status,'success');assert.equal(b.rows[1][2],long.trim());assert.equal(b.post({action:'create',...valid,description:'singkat'}).code,'VALIDATION_ERROR');});

test('Thumbnail Drive, Googleusercontent dan gambar langsung didukung pada frontend dan backend',()=>{const b=backend();const pairs=[['https://lh3.googleusercontent.com/d/abcdefghijk123456','https://drive.google.com/thumbnail?id=abcdefghijk123456&sz=w1200'],[' https://drive.google.com/file/d/abcdefghijk123456/view?usp=sharing ','https://drive.google.com/thumbnail?id=abcdefghijk123456&sz=w1200'],['https://i.postimg.cc/abc/gambar.png','https://i.postimg.cc/abc/gambar.png'],['https://images.unsplash.com/photo-123?w=600','https://images.unsplash.com/photo-123?w=600']];for(const [input,expected] of pairs){assert.equal(thumbnail(input),expected);assert.equal(b.ctx.thumbnail_(input),expected);assert.equal(validate({...valid,thumbnail:input}).thumbnail,undefined);assert.equal(b.post({action:'create',...valid,title:'Media '+input,thumbnail:input}).status,'success');}for(const input of ['https://drive.google.com/drive/folders/abcdefghijk123456','https://images.unsplashhttps://drive.google.com/drive/folders/broken','https://freeimage.host/i/nqVaVGn','javascript:alert(1)','https://127.0.0.1/a.png']){assert.equal(thumbnail(input),'');assert.equal(b.ctx.thumbnail_(input),'');}const row=[...b.rows[1]];row[3]='https://lh3.googleusercontent.com/d/abcdefghijk123456';assert.equal(b.ctx.publicRow_(row).thumbnail,pairs[0][1]);});
